"use client";

import { useMemo, useState } from "react";

type Resource = { id: string; title: string; description: string; curriculum: "CBC" | "8-4-4" | "IGCSE" | "Global"; grade: string; subject: string; type: "Exam" | "Lesson Plan" | "Notes"; priceKes: number; priceUsd: number; preview: string };
const resources: Resource[] = [
  { id: "1", title: "Grade 6 Integrated Science Revision", description: "Curriculum-aligned practice questions with answer guide.", curriculum: "CBC", grade: "Grade 6", subject: "Integrated Science", type: "Exam", priceKes: 180, priceUsd: 1.5, preview: "Science" },
  { id: "2", title: "KCSE Mathematics Paper 2 Pack", description: "Targeted algebra, geometry and statistics practice.", curriculum: "8-4-4", grade: "Form 4", subject: "Mathematics", type: "Exam", priceKes: 250, priceUsd: 2, preview: "Mathematics" },
  { id: "3", title: "IGCSE Biology: Cells & Organisation", description: "Clear notes, diagrams and self-check activities.", curriculum: "IGCSE", grade: "Year 10", subject: "Biology", type: "Notes", priceKes: 300, priceUsd: 2.5, preview: "Biology" },
];
const selectClass = "w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";

function Preview({ resource }: { resource: Resource }) {
  return <div className="relative aspect-[16/10] select-none overflow-hidden rounded-2xl bg-gradient-to-br from-blue-600 via-blue-500 to-emerald-400 p-5 text-white" onContextMenu={(event) => event.preventDefault()} onCopy={(event) => event.preventDefault()}>
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_10%,rgba(255,255,255,.28),transparent_25%)]" />
    <span className="relative inline-flex rounded-full bg-white/20 px-3 py-1 text-xs font-semibold backdrop-blur">Preview</span>
    <p className="relative mt-8 text-xl font-bold leading-tight">{resource.preview}</p>
    <p className="relative mt-1 text-sm text-blue-50">Study resource sample</p>
    <div className="absolute inset-0 grid place-items-center"><span className="rotate-[-24deg] text-2xl font-black tracking-[.35em] text-white/20">SOMA</span></div>
  </div>;
}

export default function MarketplacePage() {
  const [filters, setFilters] = useState({ curriculum: "All", grade: "All", subject: "All" });
  const [mobileFilters, setMobileFilters] = useState(false);
  const visible = useMemo(() => resources.filter((item) => (filters.curriculum === "All" || item.curriculum === filters.curriculum) && (filters.grade === "All" || item.grade === filters.grade) && (filters.subject === "All" || item.subject === filters.subject)), [filters]);
  const control = (key: keyof typeof filters, choices: string[]) => <select aria-label={`Filter by ${key}`} className={selectClass} value={filters[key]} onChange={(event) => setFilters({ ...filters, [key]: event.target.value })}>{choices.map((choice) => <option key={choice}>{choice}</option>)}</select>;
  return <main className="min-h-screen bg-slate-50 text-slate-900">
    <header className="border-b border-slate-100 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><a className="text-xl font-black tracking-tight text-blue-700" href="#top">soma<span className="text-emerald-500">.ke</span></a><nav className="hidden gap-6 text-sm font-semibold text-slate-600 sm:flex"><a href="#browse">Browse</a><a href="#sell">Sell resources</a></nav><button className="rounded-xl bg-blue-700 px-4 py-2 text-sm font-bold text-white shadow-sm hover:bg-blue-800">Sign in</button></div></header>
    <section id="top" className="overflow-hidden bg-blue-700"><div className="mx-auto grid max-w-7xl gap-9 px-4 py-16 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:py-24"><div><p className="mb-4 inline-flex rounded-full bg-white/15 px-3 py-1 text-sm font-bold text-emerald-200">Made for every classroom</p><h1 className="max-w-xl text-4xl font-black tracking-tight text-white sm:text-6xl">Great resources. Confident learners.</h1><p className="mt-5 max-w-lg text-lg leading-8 text-blue-100">Discover trusted CBC, 8-4-4, IGCSE and IB-ready learning materials — created by educators, for learners everywhere.</p><a href="#browse" className="mt-8 inline-flex rounded-xl bg-emerald-400 px-5 py-3 font-bold text-slate-950 hover:bg-emerald-300">Explore resources</a></div><div className="rounded-3xl bg-white/10 p-6 backdrop-blur"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white p-5 text-slate-900"><p className="text-3xl">🇰🇪</p><p className="mt-4 font-bold">Kenyan curricula</p><p className="mt-1 text-sm text-slate-500">CBC and 8-4-4</p></div><div className="rounded-2xl bg-emerald-400 p-5 text-slate-950"><p className="text-3xl">🌍</p><p className="mt-4 font-bold">Global learning</p><p className="mt-1 text-sm text-emerald-950/70">IGCSE and IB-ready</p></div></div><p className="mt-5 text-sm font-medium text-blue-100">Pay securely with M-Pesa, Airtel Money, Visa or Mastercard.</p></div></div></section>
    <section id="browse" className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wider text-emerald-600">Resource library</p><h2 className="mt-1 text-3xl font-black">Find your next lesson</h2></div><button onClick={() => setMobileFilters(!mobileFilters)} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold md:hidden">Filters</button></div><div className={`${mobileFilters ? "grid" : "hidden"} mt-6 gap-3 rounded-2xl bg-white p-4 shadow-sm md:grid md:grid-cols-3 md:bg-transparent md:p-0 md:shadow-none`}>{control("curriculum", ["All", "CBC", "8-4-4", "IGCSE", "Global"])}{control("grade", ["All", "Grade 6", "Form 4", "Year 10"])}{control("subject", ["All", "Integrated Science", "Mathematics", "Biology"])}</div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map((resource) => <article key={resource.id} className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><Preview resource={resource} /><div className="p-5"><div className="flex gap-2"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{resource.curriculum}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{resource.grade}</span></div><h3 className="mt-4 text-lg font-extrabold">{resource.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{resource.description}</p><div className="mt-5 flex items-center justify-between"><p className="font-black text-blue-700">KSh {resource.priceKes} <span className="text-xs font-semibold text-slate-400">/ ${resource.priceUsd}</span></p><button className="rounded-xl bg-blue-700 px-4 py-2 text-sm font-bold text-white hover:bg-blue-800">View</button></div></div></article>)}</div>{visible.length === 0 && <p className="py-16 text-center text-slate-500">No resources match those filters yet.</p>}</section>
  </main>;
}
